use std::path::Path;
use std::sync::OnceLock;

use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

const SCHEMA: &str = "
CREATE TABLE IF NOT EXISTS highlights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id TEXT NOT NULL,
    color TEXT NOT NULL,
    text_range_start INTEGER NOT NULL,
    text_range_end INTEGER NOT NULL,
    selected_text TEXT NOT NULL,
    field TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_highlights_verse ON highlights(verse_id);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id TEXT NOT NULL UNIQUE,
    title TEXT,
    content_json TEXT NOT NULL,
    content_text TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS bookmarks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id TEXT NOT NULL UNIQUE,
    book_title TEXT NOT NULL,
    verse_ref TEXT NOT NULL,
    tag TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS reading_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id TEXT NOT NULL,
    book_title TEXT NOT NULL,
    verse_ref TEXT NOT NULL,
    timestamp TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_history_timestamp ON reading_history(timestamp DESC);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS book_folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS book_folder_members (
    folder_id INTEGER NOT NULL REFERENCES book_folders(id) ON DELETE CASCADE,
    book_key TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (folder_id, book_key)
);
";

/// Opens (creating if necessary) the read-write user data database and runs
/// the idempotent schema migration. WAL mode is enabled here — unlike the
/// read-only corpus, this database is actually written to by the app, so WAL
/// lets reads and writes proceed without blocking each other.
/// True if `table` already has a column named `column` — SQLite's
/// `ALTER TABLE ... ADD COLUMN` has no `IF NOT EXISTS` form, so additive
/// migrations on a database that predates this column must check first
/// (safe against injection: `table`/`column` are always our own hardcoded
/// literals below, never user input).
fn column_exists(conn: &Connection, table: &str, column: &str) -> rusqlite::Result<bool> {
    let mut stmt = conn.prepare(&format!("PRAGMA table_info({table})"))?;
    let exists = stmt
        .query_map([], |row| row.get::<_, String>(1))?
        .filter_map(|r| r.ok())
        .any(|name| name == column);
    Ok(exists)
}

pub fn open_and_migrate(path: &Path) -> rusqlite::Result<Connection> {
    let conn = Connection::open(path)?;
    // `journal_mode` always returns the resulting mode as a result row, even
    // when "set" via PRAGMA — pragma_update accounts for that, whereas plain
    // execute_batch rejects statements that return rows.
    conn.pragma_update_and_check(None, "journal_mode", "WAL", |_row| Ok(()))?;
    conn.pragma_update(None, "foreign_keys", "ON")?;
    conn.execute_batch(SCHEMA)?;

    // Additive migrations for columns introduced after the tables above
    // first shipped — `CREATE TABLE IF NOT EXISTS` alone doesn't add them to
    // an already-existing database.
    if !column_exists(&conn, "highlights", "field")? {
        conn.execute_batch("ALTER TABLE highlights ADD COLUMN field TEXT")?;
    }
    if !column_exists(&conn, "notes", "title")? {
        conn.execute_batch("ALTER TABLE notes ADD COLUMN title TEXT")?;
    }
    // Stable cross-device identity for cloud sync — v2's `UserBookmark.Id` is
    // a GUID assigned at creation, independent of `verse_id`; the local
    // autoincrement `id` can't fill that role (it's per-database, so two
    // devices' bookmarks for the same verse would get different Supabase
    // rows). `remote_id` is generated by the sync layer on first push (or
    // adopted from a pulled row) and reused on every push after that.
    if !column_exists(&conn, "bookmarks", "remote_id")? {
        conn.execute_batch("ALTER TABLE bookmarks ADD COLUMN remote_id TEXT")?;
    }
    // Soft-delete: v2 pushes a `deleted_at` tombstone when a bookmark is
    // removed, so another device's next pull knows to retract it too. A
    // hard `DELETE` here would push nothing on the next sync, leaving v2
    // (or any other device) holding a bookmark this one already removed —
    // it would look like the deletion silently didn't sync.
    if !column_exists(&conn, "bookmarks", "deleted_at")? {
        conn.execute_batch("ALTER TABLE bookmarks ADD COLUMN deleted_at TEXT")?;
    }
    // Same stable cross-device identity + tombstone pattern as bookmarks
    // above, now extended to notes and highlights — without `remote_id`,
    // every push synthesized a fresh id from local data (verse_id for
    // notes, a verse+range+color composite for highlights) instead of
    // reusing the row's real Supabase id, so every device's push forked its
    // own duplicate remote row. Without `deleted_at`, `delete_note`/
    // `delete_highlight` hard-deleted, leaving nothing to push as a
    // tombstone — a deletion on one device never reached any other.
    if !column_exists(&conn, "notes", "remote_id")? {
        conn.execute_batch("ALTER TABLE notes ADD COLUMN remote_id TEXT")?;
    }
    if !column_exists(&conn, "notes", "deleted_at")? {
        conn.execute_batch("ALTER TABLE notes ADD COLUMN deleted_at TEXT")?;
    }
    if !column_exists(&conn, "highlights", "remote_id")? {
        conn.execute_batch("ALTER TABLE highlights ADD COLUMN remote_id TEXT")?;
    }
    if !column_exists(&conn, "highlights", "deleted_at")? {
        conn.execute_batch("ALTER TABLE highlights ADD COLUMN deleted_at TEXT")?;
    }
    // v3 has no local collections table (a bookmark's `tag` string doubles
    // as its collection's name), so there's nowhere to persist the stable
    // Supabase id of the collection a bookmark belongs to — every push used
    // to derive a fresh id by hashing the tag name instead, which collides
    // with nothing a pre-existing v2 collection (random GUID) ever used,
    // producing a second, duplicate-named collection in Supabase (and then
    // in v2) on every sync. Storing the real id once it's known (pulled, or
    // discovered on first push) and reusing it from then on fixes that.
    if !column_exists(&conn, "bookmarks", "remote_collection_id")? {
        conn.execute_batch("ALTER TABLE bookmarks ADD COLUMN remote_collection_id TEXT")?;
    }
    // Unlike notes/highlights, bookmarks never got an `updated_at` column —
    // every mutation (collection rename, tag change, soft-delete) left the
    // row's only timestamp at its original `created_at`. The sync push sent
    // that unchanged value, so v2's incremental pull (`updated_at >
    // watermark`) never saw the edit at all.
    if !column_exists(&conn, "bookmarks", "updated_at")? {
        conn.execute_batch(
            "ALTER TABLE bookmarks ADD COLUMN updated_at TEXT;
             UPDATE bookmarks SET updated_at = created_at WHERE updated_at IS NULL;",
        )?;
    }

    // v2 supports standalone (not verse-anchored) research notes and
    // multiple notes on the same verse; the original schema's
    // `verse_id TEXT NOT NULL UNIQUE` ruled out both, silently dropping any
    // such note pulled from Supabase and capping every verse at one local
    // note. Neither constraint can be altered in place in SQLite, so this
    // rebuilds the table — guarded on `verse_id` still being NOT NULL so it
    // only ever runs once per database.
    if notes_verse_id_is_not_null(&conn)? {
        conn.execute_batch(
            "CREATE TABLE notes_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                verse_id TEXT,
                title TEXT,
                content_json TEXT NOT NULL,
                content_text TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
                updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
                remote_id TEXT,
                deleted_at TEXT
             );
             INSERT INTO notes_new (id, verse_id, title, content_json, content_text, created_at, updated_at, remote_id, deleted_at)
                SELECT id, verse_id, title, content_json, content_text, created_at, updated_at, remote_id, deleted_at FROM notes;
             DROP TABLE notes;
             ALTER TABLE notes_new RENAME TO notes;
             CREATE INDEX IF NOT EXISTS idx_notes_verse ON notes(verse_id);",
        )?;
    }

    Ok(conn)
}

/// True if `notes.verse_id` still has its original `NOT NULL` constraint —
/// the one-shot guard for the standalone-notes/multi-note-per-verse
/// migration above (SQLite's `PRAGMA table_info` has no equivalent flag for
/// `UNIQUE`, but that constraint was introduced and is removed in the exact
/// same rebuild, so this alone is a reliable "already migrated?" check).
fn notes_verse_id_is_not_null(conn: &Connection) -> rusqlite::Result<bool> {
    let mut stmt = conn.prepare("PRAGMA table_info(notes)")?;
    let rows = stmt.query_map([], |row| Ok((row.get::<_, String>(1)?, row.get::<_, i64>(3)?)))?;
    for row in rows {
        let (name, notnull) = row?;
        if name == "verse_id" {
            return Ok(notnull != 0);
        }
    }
    Ok(false)
}

// ---------------------------------------------------------------------------
// Highlights
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Highlight {
    pub id: i64,
    pub verse_id: String,
    pub color: String,
    pub text_range_start: i64,
    pub text_range_end: i64,
    pub selected_text: String,
    /// Which verse field the selection was made in — `"translation"` |
    /// `"synonyms"` | `"purport"` | `None` for highlights made before this
    /// column existed. Matches v2's Supabase `vb_highlights.field` values.
    pub field: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    /// Supabase `vb_highlights.id` this highlight last synced under — null
    /// until the first push (or pull) assigns one. See `supabaseSync.ts`.
    pub remote_id: Option<String>,
    /// Set when soft-deleted locally; only present on rows from
    /// `get_all_highlights_for_sync` (`get_all_highlights`/
    /// `get_highlights_for_verse` never return one).
    pub deleted_at: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewHighlight {
    pub verse_id: String,
    pub color: String,
    pub text_range_start: i64,
    pub text_range_end: i64,
    pub selected_text: String,
    #[serde(default)]
    pub field: Option<String>,
}

fn row_to_highlight(row: &rusqlite::Row) -> rusqlite::Result<Highlight> {
    Ok(Highlight {
        id: row.get(0)?,
        verse_id: row.get(1)?,
        color: row.get(2)?,
        text_range_start: row.get(3)?,
        text_range_end: row.get(4)?,
        selected_text: row.get(5)?,
        field: row.get(6)?,
        created_at: row.get(7)?,
        updated_at: row.get(8)?,
        remote_id: row.get(9)?,
        deleted_at: row.get(10)?,
    })
}

const HIGHLIGHT_COLUMNS: &str = "id, verse_id, color, text_range_start, text_range_end, selected_text, field, created_at, updated_at, remote_id, deleted_at";

pub fn save_highlight(conn: &Connection, h: NewHighlight) -> rusqlite::Result<Highlight> {
    conn.execute(
        "INSERT INTO highlights (verse_id, color, text_range_start, text_range_end, selected_text, field) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![h.verse_id, h.color, h.text_range_start, h.text_range_end, h.selected_text, h.field],
    )?;
    let id = conn.last_insert_rowid();
    conn.query_row(
        &format!("SELECT {HIGHLIGHT_COLUMNS} FROM highlights WHERE id = ?1"),
        [id],
        row_to_highlight,
    )
}

/// Soft-delete: keeps the row (with its `remote_id`) so the next sync push
/// can carry a `deleted_at` tombstone to Supabase — see `remove_bookmark`'s
/// doc comment for why a hard `DELETE` here would silently fail to sync the
/// deletion to any other device.
pub fn delete_highlight(conn: &Connection, id: i64) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE highlights SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?1",
        [id],
    )?;
    Ok(())
}

pub fn get_highlights_for_verse(conn: &Connection, verse_id: &str) -> rusqlite::Result<Vec<Highlight>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {HIGHLIGHT_COLUMNS} FROM highlights WHERE verse_id = ?1 AND deleted_at IS NULL ORDER BY text_range_start"
    ))?;
    let result = stmt.query_map([verse_id], row_to_highlight)?.collect();
    result
}

pub fn get_all_highlights(conn: &Connection) -> rusqlite::Result<Vec<Highlight>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {HIGHLIGHT_COLUMNS} FROM highlights WHERE deleted_at IS NULL ORDER BY created_at DESC"
    ))?;
    let result = stmt.query_map([], row_to_highlight)?.collect();
    result
}

/// Every highlight including soft-deleted ones — only the sync push path
/// needs these (to carry a tombstone up); everywhere else `get_all_highlights`
/// (active-only) is the right call.
pub fn get_all_highlights_for_sync(conn: &Connection) -> rusqlite::Result<Vec<Highlight>> {
    let mut stmt =
        conn.prepare(&format!("SELECT {HIGHLIGHT_COLUMNS} FROM highlights ORDER BY created_at DESC"))?;
    let result = stmt.query_map([], row_to_highlight)?.collect();
    result
}

/// Records the Supabase row id a highlight is (or should be) synced under —
/// same role as `set_bookmark_remote_id`, keyed by the local autoincrement
/// `id` since highlights have no other stable local identity.
pub fn set_highlight_remote_id(conn: &Connection, id: i64, remote_id: &str) -> rusqlite::Result<()> {
    conn.execute("UPDATE highlights SET remote_id = ?1 WHERE id = ?2", params![remote_id, id])?;
    Ok(())
}

/// Applies a deletion that happened on another device: soft-deletes
/// whichever local highlight (if any) carries this `remote_id`. A no-op if
/// this device has never synced that row (nothing to retract).
pub fn apply_highlight_tombstone(conn: &Connection, remote_id: &str, deleted_at: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE highlights SET deleted_at = ?1 WHERE remote_id = ?2",
        params![deleted_at, remote_id],
    )?;
    Ok(())
}

/// Upserts a highlight pulled from cloud sync. Highlights have no single
/// natural-key column locally (unlike notes/bookmarks' `UNIQUE(verse_id)`),
/// so this matches on the same composite key the sync layer used to use as
/// the remote row's id (`verse_id` + range + color) to stay idempotent
/// across repeated pulls instead of duplicating the row every time — and
/// additionally keys on `remote_id` once a row has one, since the
/// composite key is no longer what the remote row is actually pushed under
/// (see `supabaseSync.ts`'s `pushAll`). `deleted_at` is explicitly cleared:
/// a pull only ever sees non-tombstoned remote rows, so one existing here
/// means it's current and should un-delete a stale local soft-delete,
/// matching `add_bookmark`'s same `deleted_at = NULL` precedent.
/// `remote_id` is `None` for a non-sync caller (the `.vdbbackup` local file
/// importer) that has no Supabase row to associate yet — it leaves any
/// existing `remote_id` untouched (`COALESCE`) rather than clobbering a
/// highlight's real sync identity back to unset.
#[allow(clippy::too_many_arguments)]
pub fn upsert_synced_highlight(
    conn: &Connection,
    verse_id: &str,
    color: &str,
    text_range_start: i64,
    text_range_end: i64,
    selected_text: &str,
    field: Option<&str>,
    created_at: &str,
    updated_at: &str,
    remote_id: Option<&str>,
) -> rusqlite::Result<()> {
    let existing_id: Option<i64> = conn
        .query_row(
            "SELECT id FROM highlights WHERE (?1 IS NOT NULL AND remote_id = ?1) \
             OR (verse_id = ?2 AND text_range_start = ?3 AND text_range_end = ?4 AND color = ?5)",
            params![remote_id, verse_id, text_range_start, text_range_end, color],
            |r| r.get(0),
        )
        .optional()?;

    match existing_id {
        Some(id) => {
            conn.execute(
                "UPDATE highlights SET selected_text = ?1, field = ?2, updated_at = ?3, remote_id = COALESCE(?4, remote_id), deleted_at = NULL WHERE id = ?5",
                params![selected_text, field, updated_at, remote_id, id],
            )?;
        }
        None => {
            conn.execute(
                "INSERT INTO highlights (verse_id, color, text_range_start, text_range_end, selected_text, field, created_at, updated_at, remote_id) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
                params![verse_id, color, text_range_start, text_range_end, selected_text, field, created_at, updated_at, remote_id],
            )?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Notes (one per verse — upsert on save)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Note {
    pub id: i64,
    /// `None` for a standalone research note (v2's `RecordKey = NULL`) —
    /// not anchored to any verse.
    pub verse_id: Option<String>,
    pub title: Option<String>,
    pub content_json: String,
    pub content_text: String,
    pub created_at: String,
    pub updated_at: String,
    /// Supabase `vb_notes.id` this note last synced under — null until the
    /// first push (or pull) assigns one. See `supabaseSync.ts`.
    pub remote_id: Option<String>,
    /// Set when soft-deleted locally; only present on rows from
    /// `get_all_notes_for_sync` (`get_all_notes`/`get_note_for_verse` never
    /// return one).
    pub deleted_at: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewNote {
    /// `None` creates a standalone research note, not anchored to any verse.
    #[serde(default)]
    pub verse_id: Option<String>,
    #[serde(default)]
    pub title: Option<String>,
    pub content_json: String,
    pub content_text: String,
}

fn row_to_note(row: &rusqlite::Row) -> rusqlite::Result<Note> {
    Ok(Note {
        id: row.get(0)?,
        verse_id: row.get(1)?,
        title: row.get(2)?,
        content_json: row.get(3)?,
        content_text: row.get(4)?,
        created_at: row.get(5)?,
        updated_at: row.get(6)?,
        remote_id: row.get(7)?,
        deleted_at: row.get(8)?,
    })
}

const NOTE_COLUMNS: &str = "id, verse_id, title, content_json, content_text, created_at, updated_at, remote_id, deleted_at";

/// Always inserts a new row — unlike the old one-note-per-verse scheme,
/// there's no existing row to upsert onto by `verse_id` anymore (multiple
/// notes can share a verse, and a standalone note has no `verse_id` at
/// all), so "create" and "edit" are necessarily two different operations
/// now (see `update_note`).
pub fn create_note(conn: &Connection, n: NewNote) -> rusqlite::Result<Note> {
    conn.execute(
        "INSERT INTO notes (verse_id, title, content_json, content_text) VALUES (?1, ?2, ?3, ?4)",
        params![n.verse_id, n.title, n.content_json, n.content_text],
    )?;
    let id = conn.last_insert_rowid();
    conn.query_row(&format!("SELECT {NOTE_COLUMNS} FROM notes WHERE id = ?1"), [id], row_to_note)
}

/// Edits an existing note's content in place, identified by its own `id` —
/// `verse_id` can no longer identify "the" note to update since a verse may
/// have several. Reviving a previously soft-deleted note (rather than
/// leaving a dangling tombstone next to fresh content) is intentional here
/// too, same reasoning as `add_bookmark`'s `deleted_at = NULL`.
pub fn update_note(
    conn: &Connection,
    id: i64,
    title: Option<&str>,
    content_json: &str,
    content_text: &str,
) -> rusqlite::Result<Note> {
    conn.execute(
        "UPDATE notes SET title = ?1, content_json = ?2, content_text = ?3, deleted_at = NULL, \
         updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?4",
        params![title, content_json, content_text, id],
    )?;
    conn.query_row(&format!("SELECT {NOTE_COLUMNS} FROM notes WHERE id = ?1"), [id], row_to_note)
}

/// Soft-delete: keeps the row (with its `remote_id`) so the next sync push
/// can carry a `deleted_at` tombstone to Supabase — see `remove_bookmark`'s
/// doc comment for why a hard `DELETE` here would silently fail to sync the
/// deletion to any other device. Identified by `id`, not `verse_id` (no
/// longer unique, and `None` for standalone notes).
pub fn delete_note(conn: &Connection, id: i64) -> rusqlite::Result<()> {
    conn.execute("UPDATE notes SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?1", [id])?;
    Ok(())
}

/// Every active note anchored to this verse — zero, one, or many.
pub fn get_notes_for_verse(conn: &Connection, verse_id: &str) -> rusqlite::Result<Vec<Note>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {NOTE_COLUMNS} FROM notes WHERE verse_id = ?1 AND deleted_at IS NULL ORDER BY created_at"
    ))?;
    let result = stmt.query_map([verse_id], row_to_note)?.collect();
    result
}

pub fn get_all_notes(conn: &Connection) -> rusqlite::Result<Vec<Note>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {NOTE_COLUMNS} FROM notes WHERE deleted_at IS NULL ORDER BY updated_at DESC"
    ))?;
    let result = stmt.query_map([], row_to_note)?.collect();
    result
}

/// Every note including soft-deleted ones — only the sync push path needs
/// these (to carry a tombstone up); everywhere else `get_all_notes`
/// (active-only) is the right call.
pub fn get_all_notes_for_sync(conn: &Connection) -> rusqlite::Result<Vec<Note>> {
    let mut stmt = conn.prepare(&format!("SELECT {NOTE_COLUMNS} FROM notes ORDER BY updated_at DESC"))?;
    let result = stmt.query_map([], row_to_note)?.collect();
    result
}

/// Records the Supabase row id a note is (or should be) synced under —
/// identified by `id` now (not `verse_id`, which no longer uniquely
/// identifies a note, and `None` for standalone notes).
pub fn set_note_remote_id(conn: &Connection, id: i64, remote_id: &str) -> rusqlite::Result<()> {
    conn.execute("UPDATE notes SET remote_id = ?1 WHERE id = ?2", params![remote_id, id])?;
    Ok(())
}

/// Applies a deletion that happened on another device: soft-deletes
/// whichever local note (if any) carries this `remote_id`. A no-op if this
/// device has never synced that row (nothing to retract).
pub fn apply_note_tombstone(conn: &Connection, remote_id: &str, deleted_at: &str) -> rusqlite::Result<()> {
    conn.execute("UPDATE notes SET deleted_at = ?1 WHERE remote_id = ?2", params![deleted_at, remote_id])?;
    Ok(())
}

/// Upserts a note pulled from cloud sync — parallel to
/// `upsert_synced_highlight`, kept separate from `create_note`/`update_note`
/// (the local-edit paths) so a plain local save can never accidentally
/// stamp a `remote_id` a pull hasn't actually confirmed. Matches the
/// existing local row by `remote_id` alone now — `verse_id` can no longer
/// identify "the" note for a conflict target once multiple notes can share
/// one (or have none at all). `deleted_at` is explicitly cleared for the
/// same reason `upsert_synced_highlight` clears it: a pull only ever sees
/// non-tombstoned remote rows.
pub fn upsert_synced_note(
    conn: &Connection,
    verse_id: Option<&str>,
    title: Option<&str>,
    content_text: &str,
    content_json: &str,
    remote_id: &str,
    created_at: &str,
    updated_at: &str,
) -> rusqlite::Result<()> {
    let existing_id: Option<i64> =
        conn.query_row("SELECT id FROM notes WHERE remote_id = ?1", [remote_id], |r| r.get(0)).optional()?;

    match existing_id {
        Some(id) => {
            conn.execute(
                "UPDATE notes SET verse_id = ?1, title = ?2, content_json = ?3, content_text = ?4, \
                 updated_at = ?5, deleted_at = NULL WHERE id = ?6",
                params![verse_id, title, content_json, content_text, updated_at, id],
            )?;
        }
        None => {
            conn.execute(
                "INSERT INTO notes (verse_id, title, content_json, content_text, remote_id, created_at, updated_at) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
                params![verse_id, title, content_json, content_text, remote_id, created_at, updated_at],
            )?;
        }
    }
    Ok(())
}

/// Extracts unique `#hashtag` occurrences from note content, in first-seen
/// order — the note tag cloud (frontend) and each note's YAML frontmatter
/// `tags:` list (Obsidian export, below) both build on this.
pub fn extract_tags(content_text: &str) -> Vec<String> {
    static TAG_RE: OnceLock<regex::Regex> = OnceLock::new();
    let re = TAG_RE.get_or_init(|| regex::Regex::new(r"#([a-zA-Z0-9_-]+)").unwrap());
    let mut seen = std::collections::HashSet::new();
    let mut tags = Vec::new();
    for cap in re.captures_iter(content_text) {
        let tag = cap[1].to_string();
        if seen.insert(tag.clone()) {
            tags.push(tag);
        }
    }
    tags
}

fn sanitize_filename_component(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| if c.is_alphanumeric() || c == ' ' || c == '-' || c == '_' { c } else { '-' })
        .collect();
    let trimmed = cleaned.trim();
    if trimmed.is_empty() { "Untitled".to_string() } else { trimmed.to_string() }
}

/// One Markdown file per note, Obsidian-compatible (YAML frontmatter +
/// `#tags` inline, `[[WikiLinks]]` are already plain Obsidian syntax the
/// note body may contain as-is) — the command layer zips these together.
/// Filenames are de-duplicated by appending the note's id when two notes
/// would otherwise sanitize to the same name.
pub fn build_obsidian_notes(notes: &[Note]) -> Vec<(String, String)> {
    let mut used_names = std::collections::HashSet::new();
    notes
        .iter()
        .map(|n| {
            let record_key = n.verse_id.as_deref().unwrap_or("standalone");
            let title = n.title.clone().unwrap_or_else(|| record_key.to_string());
            let base = sanitize_filename_component(&title);
            let filename = if used_names.insert(base.clone()) {
                format!("{base}.md")
            } else {
                format!("{base}-{}.md", n.id)
            };
            let tags = extract_tags(&n.content_text);
            let tags_yaml = if tags.is_empty() {
                "[]".to_string()
            } else {
                format!("[{}]", tags.iter().map(|t| format!("\"{t}\"")).collect::<Vec<_>>().join(", "))
            };
            let content = format!(
                "---\ntitle: \"{}\"\nrecord_key: \"{}\"\ntags: {}\ncreated: {}\nupdated: {}\n---\n\n{}\n",
                title.replace('"', "'"),
                record_key,
                tags_yaml,
                n.created_at,
                n.updated_at,
                n.content_text,
            );
            (filename, content)
        })
        .collect()
}

/// All notes concatenated into a single Markdown document (the "Export
/// Markdown" — as opposed to "Export Obsidian Vault" — button).
pub fn build_markdown_export(notes: &[Note]) -> String {
    let mut out = String::new();
    for n in notes {
        let record_key = n.verse_id.as_deref().unwrap_or("Standalone");
        let title = n.title.clone().unwrap_or_else(|| record_key.to_string());
        out.push_str(&format!("## {title}\n\n"));
        out.push_str(&format!("*{} — updated {}*\n\n", record_key, n.updated_at));
        out.push_str(&n.content_text);
        out.push_str("\n\n---\n\n");
    }
    out
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

/// A self-contained styled HTML document of every note — the "Print / PDF"
/// export, opened in the system browser so the OS's own print dialog (and
/// its "Save as PDF" option) handles the rest; no PDF-rendering dependency
/// needed here.
pub fn build_html_export(notes: &[Note]) -> String {
    let rows: String = notes
        .iter()
        .map(|n| {
            let title = html_escape(n.title.as_deref().unwrap_or("Untitled Note"));
            let verse = html_escape(n.verse_id.as_deref().unwrap_or("Standalone"));
            let body = html_escape(&n.content_text);
            let date = n.created_at.get(..10).unwrap_or(&n.created_at);
            format!(
                "<div class=\"note\"><h2>{title}</h2><div class=\"meta\">{verse} · {date}</div><pre>{body}</pre></div>"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Prabhupāda Connect — Notes</title>
<style>
  body {{ font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.7; }}
  h1 {{ font-size: 1.6em; border-bottom: 2px solid #c9a84c; padding-bottom: 8px; color: #8b5e1a; }}
  .note {{ margin: 32px 0; padding: 24px; border: 1px solid #ddd; border-radius: 8px; page-break-inside: avoid; }}
  .note h2 {{ margin: 0 0 4px 0; font-size: 1.1em; color: #333; }}
  .meta {{ font-size: 0.8em; color: #888; margin-bottom: 12px; }}
  pre {{ white-space: pre-wrap; font-family: inherit; margin: 0; font-size: 0.95em; }}
  @media print {{ body {{ margin: 20px; }} .no-print {{ display: none; }} }}
</style>
</head>
<body>
<div class="no-print" style="text-align:right;padding:8px 16px;">
  <small style="color:#888">Print dialog will open automatically. Close this tab when done.</small>
</div>
<h1>Prabhupāda Connect — Personal Realizations &amp; Notes</h1>
{rows}
<script>
  // Delay slightly so the browser has rendered before opening the print dialog.
  setTimeout(function() {{ window.print(); }}, 400);
</script>
</body>
</html>"#
    )
}

// ---------------------------------------------------------------------------
// Bookmarks (one per verse — re-adding replaces the tag)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Bookmark {
    pub id: i64,
    pub verse_id: String,
    pub book_title: String,
    pub verse_ref: String,
    pub tag: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub remote_id: Option<String>,
    pub deleted_at: Option<String>,
    /// Supabase `vb_bookmark_collections.id` this bookmark's `tag` collection
    /// last synced under — null until discovered (pulled) or minted (first
    /// push of a never-before-synced collection). See `set_bookmark_remote_collection_id`.
    pub remote_collection_id: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewBookmark {
    pub verse_id: String,
    pub book_title: String,
    pub verse_ref: String,
    pub tag: Option<String>,
}

fn row_to_bookmark(row: &rusqlite::Row) -> rusqlite::Result<Bookmark> {
    Ok(Bookmark {
        id: row.get(0)?,
        verse_id: row.get(1)?,
        book_title: row.get(2)?,
        verse_ref: row.get(3)?,
        tag: row.get(4)?,
        created_at: row.get(5)?,
        updated_at: row.get(6)?,
        remote_id: row.get(7)?,
        deleted_at: row.get(8)?,
        remote_collection_id: row.get(9)?,
    })
}

const BOOKMARK_COLUMNS: &str =
    "id, verse_id, book_title, verse_ref, tag, created_at, updated_at, remote_id, deleted_at, remote_collection_id";

pub fn add_bookmark(conn: &Connection, b: NewBookmark) -> rusqlite::Result<Bookmark> {
    conn.execute(
        "INSERT INTO bookmarks (verse_id, book_title, verse_ref, tag, updated_at) \
         VALUES (?1, ?2, ?3, ?4, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) \
         ON CONFLICT(verse_id) DO UPDATE SET tag = excluded.tag, deleted_at = NULL, \
         updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')",
        params![b.verse_id, b.book_title, b.verse_ref, b.tag],
    )?;
    conn.query_row(
        &format!("SELECT {BOOKMARK_COLUMNS} FROM bookmarks WHERE verse_id = ?1"),
        [b.verse_id],
        row_to_bookmark,
    )
}

/// Soft-delete: keeps the row (with its `remote_id`) so the next sync push
/// can carry a `deleted_at` tombstone to Supabase — a hard delete here would
/// have nothing left to push, and another device would never learn this
/// bookmark was removed. Re-bookmarking the same verse (`add_bookmark`)
/// clears `deleted_at`, reviving the same row rather than leaving a
/// dangling tombstone next to a fresh one.
pub fn remove_bookmark(conn: &Connection, verse_id: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), \
         updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE verse_id = ?1",
        [verse_id],
    )?;
    Ok(())
}

pub fn get_bookmarks(conn: &Connection) -> rusqlite::Result<Vec<Bookmark>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {BOOKMARK_COLUMNS} FROM bookmarks WHERE deleted_at IS NULL ORDER BY created_at DESC"
    ))?;
    let result = stmt.query_map([], row_to_bookmark)?.collect();
    result
}

/// Every bookmark row including tombstones — only the sync push path needs
/// these; everywhere else (the Bookmarks tab, search) a soft-deleted
/// bookmark should behave as gone.
pub fn get_bookmarks_for_sync(conn: &Connection) -> rusqlite::Result<Vec<Bookmark>> {
    let mut stmt = conn.prepare(&format!("SELECT {BOOKMARK_COLUMNS} FROM bookmarks ORDER BY created_at DESC"))?;
    let result = stmt.query_map([], row_to_bookmark)?.collect();
    result
}

/// Records the Supabase row id a bookmark is (or should be) synced under —
/// set once a device either generates a fresh id for a never-synced local
/// bookmark, or adopts the id of a row pulled down from another device, so
/// every later push upserts the same remote row instead of forking it.
pub fn set_bookmark_remote_id(conn: &Connection, verse_id: &str, remote_id: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET remote_id = ?1 WHERE verse_id = ?2",
        params![remote_id, verse_id],
    )?;
    Ok(())
}

/// Applies a deletion that happened on another device: soft-deletes
/// whichever local bookmark (if any) carries this `remote_id`. A no-op if
/// this device has never synced that row (nothing to retract).
pub fn apply_bookmark_tombstone(conn: &Connection, remote_id: &str, deleted_at: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET deleted_at = ?1 WHERE remote_id = ?2",
        params![deleted_at, remote_id],
    )?;
    Ok(())
}

/// Records the Supabase `vb_bookmark_collections.id` every bookmark
/// currently sharing this `tag` should push under, so the next push upserts
/// the one real remote collection instead of each device re-deriving (and
/// thereby forking) its own id for the same-named collection. Updates every
/// bookmark with this tag at once, since the collection id is shared by
/// construction (v3 has no separate collections table — see `rename_bookmark_collection`).
pub fn set_bookmark_remote_collection_id(conn: &Connection, tag: &str, remote_collection_id: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET remote_collection_id = ?1 WHERE tag = ?2",
        params![remote_collection_id, tag],
    )?;
    Ok(())
}

/// Bookmarks have no dedicated collections table — `tag` doubles as the
/// collection name (a bookmark with `tag = NULL` is "Uncategorized"), so
/// "renaming a collection" is a bulk update of every bookmark sharing that
/// tag rather than a row in some separate table.
pub fn rename_bookmark_collection(conn: &Connection, old_tag: &str, new_tag: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET tag = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE tag = ?2",
        params![new_tag, old_tag],
    )?;
    Ok(())
}

/// "Deleting a collection" clears the tag on its members (moving them to
/// Uncategorized) rather than deleting the bookmarks themselves.
pub fn clear_bookmark_collection(conn: &Connection, tag: &str) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET tag = NULL, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE tag = ?1",
        params![tag],
    )?;
    Ok(())
}

pub fn move_bookmark_to_collection(conn: &Connection, verse_id: &str, tag: Option<&str>) -> rusqlite::Result<()> {
    conn.execute(
        "UPDATE bookmarks SET tag = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE verse_id = ?2",
        params![tag, verse_id],
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Reading history (append-only log)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HistoryEntry {
    pub id: i64,
    pub verse_id: String,
    pub book_title: String,
    pub verse_ref: String,
    pub timestamp: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewHistoryEntry {
    pub verse_id: String,
    pub book_title: String,
    pub verse_ref: String,
}

fn row_to_history(row: &rusqlite::Row) -> rusqlite::Result<HistoryEntry> {
    Ok(HistoryEntry {
        id: row.get(0)?,
        verse_id: row.get(1)?,
        book_title: row.get(2)?,
        verse_ref: row.get(3)?,
        timestamp: row.get(4)?,
    })
}

const HISTORY_COLUMNS: &str = "id, verse_id, book_title, verse_ref, timestamp";

pub fn record_history(conn: &Connection, h: NewHistoryEntry) -> rusqlite::Result<HistoryEntry> {
    conn.execute(
        "INSERT INTO reading_history (verse_id, book_title, verse_ref) VALUES (?1, ?2, ?3)",
        params![h.verse_id, h.book_title, h.verse_ref],
    )?;
    let id = conn.last_insert_rowid();
    conn.query_row(
        &format!("SELECT {HISTORY_COLUMNS} FROM reading_history WHERE id = ?1"),
        [id],
        row_to_history,
    )
}

pub fn get_history(conn: &Connection, limit: i64) -> rusqlite::Result<Vec<HistoryEntry>> {
    let mut stmt = conn.prepare(&format!(
        "SELECT {HISTORY_COLUMNS} FROM reading_history ORDER BY timestamp DESC LIMIT ?1"
    ))?;
    let result = stmt.query_map([limit], row_to_history)?.collect();
    result
}

pub fn clear_history(conn: &Connection) -> rusqlite::Result<()> {
    conn.execute("DELETE FROM reading_history", [])?;
    Ok(())
}

/// Inserts a history entry pulled from cloud sync only if an entry for that
/// exact (verse, timestamp) doesn't already exist — reading history is an
/// append-only log with no unique column, so this is what keeps repeated
/// pulls from re-appending the same entries forever.
pub fn insert_history_if_absent(
    conn: &Connection,
    verse_id: &str,
    book_title: &str,
    verse_ref: &str,
    timestamp: &str,
) -> rusqlite::Result<()> {
    let exists: bool = conn.query_row(
        "SELECT EXISTS(SELECT 1 FROM reading_history WHERE verse_id = ?1 AND timestamp = ?2)",
        params![verse_id, timestamp],
        |r| r.get(0),
    )?;
    if !exists {
        conn.execute(
            "INSERT INTO reading_history (verse_id, book_title, verse_ref, timestamp) VALUES (?1, ?2, ?3, ?4)",
            params![verse_id, book_title, verse_ref, timestamp],
        )?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Unified search (Search Studio "source" filter — notes/bookmarks/highlights)
// ---------------------------------------------------------------------------
// These are plain `LIKE` substring lookups, not FTS5: the user-data tables
// are small (a personal working set, not a corpus), so an index-free scan is
// plenty fast and avoids maintaining a second set of FTS5 virtual tables for
// data that changes constantly (unlike the read-only corpus).

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteHit {
    pub verse_id: Option<String>,
    pub content_text: String,
    pub updated_at: String,
}

pub fn search_notes(conn: &Connection, query: &str, limit: i64) -> rusqlite::Result<(i64, Vec<NoteHit>)> {
    let needle = format!("%{query}%");
    let total: i64 = conn.query_row(
        "SELECT COUNT(*) FROM notes WHERE content_text LIKE ?1 OR verse_id LIKE ?1",
        [&needle],
        |r| r.get(0),
    )?;
    let mut stmt = conn.prepare(
        "SELECT verse_id, content_text, updated_at FROM notes \
         WHERE content_text LIKE ?1 OR verse_id LIKE ?1 ORDER BY updated_at DESC LIMIT ?2",
    )?;
    let rows = stmt.query_map(params![needle, limit], |row| {
        Ok(NoteHit { verse_id: row.get(0)?, content_text: row.get(1)?, updated_at: row.get(2)? })
    })?;
    Ok((total, rows.collect::<rusqlite::Result<Vec<_>>>()?))
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BookmarkHit {
    pub verse_id: String,
    pub book_title: String,
    pub verse_ref: String,
    pub tag: Option<String>,
    pub created_at: String,
}

pub fn search_bookmarks(conn: &Connection, query: &str, limit: i64) -> rusqlite::Result<(i64, Vec<BookmarkHit>)> {
    let needle = format!("%{query}%");
    let total: i64 = conn.query_row(
        "SELECT COUNT(*) FROM bookmarks WHERE deleted_at IS NULL AND (book_title LIKE ?1 OR verse_ref LIKE ?1 OR tag LIKE ?1)",
        [&needle],
        |r| r.get(0),
    )?;
    let mut stmt = conn.prepare(
        "SELECT verse_id, book_title, verse_ref, tag, created_at FROM bookmarks \
         WHERE deleted_at IS NULL AND (book_title LIKE ?1 OR verse_ref LIKE ?1 OR tag LIKE ?1) ORDER BY created_at DESC LIMIT ?2",
    )?;
    let rows = stmt.query_map(params![needle, limit], |row| {
        Ok(BookmarkHit {
            verse_id: row.get(0)?,
            book_title: row.get(1)?,
            verse_ref: row.get(2)?,
            tag: row.get(3)?,
            created_at: row.get(4)?,
        })
    })?;
    Ok((total, rows.collect::<rusqlite::Result<Vec<_>>>()?))
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HighlightHit {
    pub verse_id: String,
    pub selected_text: String,
    pub color: String,
    pub created_at: String,
}

pub fn search_highlights(conn: &Connection, query: &str, limit: i64) -> rusqlite::Result<(i64, Vec<HighlightHit>)> {
    let needle = format!("%{query}%");
    let total: i64 =
        conn.query_row("SELECT COUNT(*) FROM highlights WHERE selected_text LIKE ?1", [&needle], |r| r.get(0))?;
    let mut stmt = conn.prepare(
        "SELECT verse_id, selected_text, color, created_at FROM highlights \
         WHERE selected_text LIKE ?1 ORDER BY created_at DESC LIMIT ?2",
    )?;
    let rows = stmt.query_map(params![needle, limit], |row| {
        Ok(HighlightHit {
            verse_id: row.get(0)?,
            selected_text: row.get(1)?,
            color: row.get(2)?,
            created_at: row.get(3)?,
        })
    })?;
    Ok((total, rows.collect::<rusqlite::Result<Vec<_>>>()?))
}

// ---------------------------------------------------------------------------
// Settings (arbitrary key -> JSON value)
// ---------------------------------------------------------------------------

pub fn get_setting(conn: &Connection, key: &str) -> rusqlite::Result<Option<String>> {
    conn.query_row(
        "SELECT value_json FROM settings WHERE key = ?1",
        [key],
        |row| row.get(0),
    )
    .optional()
}

pub fn save_setting(conn: &Connection, key: &str, value_json: &str) -> rusqlite::Result<()> {
    conn.execute(
        "INSERT INTO settings (key, value_json) VALUES (?1, ?2) \
         ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json",
        params![key, value_json],
    )?;
    Ok(())
}

pub fn get_all_settings(conn: &Connection) -> rusqlite::Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare("SELECT key, value_json FROM settings")?;
    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    rows.collect()
}

// ---------------------------------------------------------------------------
// Custom book folders (Corpus & Book Management — Settings 4.8)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BookFolder {
    pub id: i64,
    pub name: String,
    pub sort_order: i64,
    pub book_keys: Vec<String>,
}

fn row_to_folder_members(conn: &Connection, folder_id: i64) -> rusqlite::Result<Vec<String>> {
    let mut stmt =
        conn.prepare("SELECT book_key FROM book_folder_members WHERE folder_id = ?1 ORDER BY sort_order")?;
    let rows = stmt.query_map([folder_id], |row| row.get::<_, String>(0))?;
    rows.collect()
}

pub fn get_book_folders(conn: &Connection) -> rusqlite::Result<Vec<BookFolder>> {
    let mut stmt = conn.prepare("SELECT id, name, sort_order FROM book_folders ORDER BY sort_order")?;
    let folders = stmt
        .query_map([], |row| Ok((row.get::<_, i64>(0)?, row.get::<_, String>(1)?, row.get::<_, i64>(2)?)))?
        .collect::<rusqlite::Result<Vec<_>>>()?;

    folders
        .into_iter()
        .map(|(id, name, sort_order)| {
            let book_keys = row_to_folder_members(conn, id)?;
            Ok(BookFolder { id, name, sort_order, book_keys })
        })
        .collect()
}

pub fn create_book_folder(conn: &Connection, name: &str) -> rusqlite::Result<BookFolder> {
    let next_order: i64 =
        conn.query_row("SELECT COALESCE(MAX(sort_order), -1) + 1 FROM book_folders", [], |r| r.get(0))?;
    conn.execute(
        "INSERT INTO book_folders (name, sort_order) VALUES (?1, ?2)",
        params![name, next_order],
    )?;
    let id = conn.last_insert_rowid();
    Ok(BookFolder { id, name: name.to_string(), sort_order: next_order, book_keys: Vec::new() })
}

pub fn rename_book_folder(conn: &Connection, id: i64, name: &str) -> rusqlite::Result<()> {
    conn.execute("UPDATE book_folders SET name = ?1 WHERE id = ?2", params![name, id])?;
    Ok(())
}

pub fn delete_book_folder(conn: &Connection, id: i64) -> rusqlite::Result<()> {
    conn.execute("DELETE FROM book_folders WHERE id = ?1", [id])?;
    Ok(())
}

/// Persists a folder's full top-to-bottom order in one call (drag-and-drop
/// "move up/down" reordering) rather than one UPDATE per swap.
pub fn reorder_book_folders(conn: &Connection, ordered_ids: &[i64]) -> rusqlite::Result<()> {
    for (i, id) in ordered_ids.iter().enumerate() {
        conn.execute("UPDATE book_folders SET sort_order = ?1 WHERE id = ?2", params![i as i64, id])?;
    }
    Ok(())
}

pub fn add_book_to_folder(conn: &Connection, folder_id: i64, book_key: &str) -> rusqlite::Result<()> {
    let next_order: i64 = conn.query_row(
        "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM book_folder_members WHERE folder_id = ?1",
        [folder_id],
        |r| r.get(0),
    )?;
    conn.execute(
        "INSERT OR IGNORE INTO book_folder_members (folder_id, book_key, sort_order) VALUES (?1, ?2, ?3)",
        params![folder_id, book_key, next_order],
    )?;
    Ok(())
}

pub fn remove_book_from_folder(conn: &Connection, folder_id: i64, book_key: &str) -> rusqlite::Result<()> {
    conn.execute(
        "DELETE FROM book_folder_members WHERE folder_id = ?1 AND book_key = ?2",
        params![folder_id, book_key],
    )?;
    Ok(())
}

pub fn reorder_books_in_folder(conn: &Connection, folder_id: i64, ordered_book_keys: &[String]) -> rusqlite::Result<()> {
    for (i, book_key) in ordered_book_keys.iter().enumerate() {
        conn.execute(
            "UPDATE book_folder_members SET sort_order = ?1 WHERE folder_id = ?2 AND book_key = ?3",
            params![i as i64, folder_id, book_key],
        )?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Backup / restore (Data & Backup — Settings 4.6)
// ---------------------------------------------------------------------------
// A full export is just every user-data row, JSON-serialized — small enough
// (personal research data, not the corpus) that there's no need for a
// streaming or chunked format.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BackupData {
    pub schema_version: i64,
    pub exported_at: String,
    pub highlights: Vec<Highlight>,
    pub notes: Vec<Note>,
    pub bookmarks: Vec<Bookmark>,
    pub history: Vec<HistoryEntry>,
    pub settings: Vec<(String, String)>,
    pub folders: Vec<BookFolder>,
}

const BACKUP_SCHEMA_VERSION: i64 = 1;

pub fn export_all(conn: &Connection) -> rusqlite::Result<BackupData> {
    Ok(BackupData {
        schema_version: BACKUP_SCHEMA_VERSION,
        exported_at: chrono_now_iso(),
        highlights: get_all_highlights(conn)?,
        notes: get_all_notes(conn)?,
        bookmarks: get_bookmarks(conn)?,
        history: get_history(conn, i64::MAX)?,
        settings: get_all_settings(conn)?,
        folders: get_book_folders(conn)?,
    })
}

/// `strftime`-based ISO-8601 timestamp, matching every other `created_at` /
/// `updated_at` column's format in this schema — avoids pulling in a whole
/// datetime crate for one string.
fn chrono_now_iso() -> String {
    // Re-use SQLite's own clock/format function rather than a Rust dependency:
    // opening a throwaway in-memory connection just for this one scalar call
    // is cheap and keeps the timestamp format byte-identical to every column
    // default above.
    let conn = Connection::open_in_memory().expect("in-memory sqlite must open");
    conn.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", [], |r| r.get(0))
        .expect("strftime must succeed")
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImportMode {
    Merge,
    Replace,
}

/// Restores a `BackupData` into the live database. `Replace` clears every
/// table first (a full restore-from-scratch); `Merge` upserts on top of
/// whatever is already there, so re-importing the same backup twice is
/// idempotent either way.
pub fn import_all(conn: &mut Connection, data: &BackupData, mode: ImportMode) -> rusqlite::Result<()> {
    let tx = conn.transaction()?;

    if mode == ImportMode::Replace {
        tx.execute_batch(
            "DELETE FROM highlights; DELETE FROM notes; DELETE FROM bookmarks; \
             DELETE FROM reading_history; DELETE FROM book_folder_members; DELETE FROM book_folders;",
        )?;
    }

    for h in &data.highlights {
        tx.execute(
            "INSERT INTO highlights (verse_id, color, text_range_start, text_range_end, selected_text, field, created_at, updated_at, remote_id, deleted_at) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
            params![h.verse_id, h.color, h.text_range_start, h.text_range_end, h.selected_text, h.field, h.created_at, h.updated_at, h.remote_id, h.deleted_at],
        )?;
    }
    // `verse_id` is no longer unique (or even present) — notes have no
    // natural key to upsert on, the same as highlights just above, so this
    // is a plain insert.
    for n in &data.notes {
        tx.execute(
            "INSERT INTO notes (verse_id, title, content_json, content_text, created_at, updated_at, remote_id, deleted_at) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            params![n.verse_id, n.title, n.content_json, n.content_text, n.created_at, n.updated_at, n.remote_id, n.deleted_at],
        )?;
    }
    for b in &data.bookmarks {
        tx.execute(
            "INSERT INTO bookmarks (verse_id, book_title, verse_ref, tag, created_at, updated_at, remote_id, deleted_at, remote_collection_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9) \
             ON CONFLICT(verse_id) DO UPDATE SET tag = excluded.tag, updated_at = excluded.updated_at, remote_id = excluded.remote_id, deleted_at = excluded.deleted_at, remote_collection_id = excluded.remote_collection_id",
            params![b.verse_id, b.book_title, b.verse_ref, b.tag, b.created_at, b.updated_at, b.remote_id, b.deleted_at, b.remote_collection_id],
        )?;
    }
    for h in &data.history {
        tx.execute(
            "INSERT INTO reading_history (verse_id, book_title, verse_ref, timestamp) VALUES (?1, ?2, ?3, ?4)",
            params![h.verse_id, h.book_title, h.verse_ref, h.timestamp],
        )?;
    }
    for (key, value_json) in &data.settings {
        tx.execute(
            "INSERT INTO settings (key, value_json) VALUES (?1, ?2) \
             ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json",
            params![key, value_json],
        )?;
    }
    for folder in &data.folders {
        tx.execute(
            "INSERT INTO book_folders (id, name, sort_order) VALUES (?1, ?2, ?3) \
             ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order",
            params![folder.id, folder.name, folder.sort_order],
        )?;
        for (i, book_key) in folder.book_keys.iter().enumerate() {
            tx.execute(
                "INSERT OR IGNORE INTO book_folder_members (folder_id, book_key, sort_order) VALUES (?1, ?2, ?3)",
                params![folder.id, book_key, i as i64],
            )?;
        }
    }

    tx.commit()
}
